export interface Skill {
  id: string;
  slug: string;
  name: string;
  creator: string;
  category: string;
  emoji: string;
  rating: number;
  ratingCount: number;
  price: string;
  priceType: "free" | "paid" | "rental";
  downloads: string;
  description: string;
  bullets: string[];
  tags: string[];
}

export const MOCK_SKILLS: Skill[] = [
  {
    id: "1",
    slug: "sous-chef-ai",
    name: "Sous Chef AI",
    creator: "@gordonbot",
    category: "Cooking",
    emoji: "🍳",
    rating: 5,
    ratingCount: 248,
    price: "Free",
    priceType: "free",
    downloads: "2.4k",
    description: "A world-class culinary assistant that helps your AI understand ingredients, recipes, cooking techniques, and flavour pairing. Built by a professional chef obsessed with automation.",
    bullets: [
      "Suggests recipes from whatever's in your fridge",
      "Explains cooking techniques in plain language",
      "Pairs wine, spices, and sides with any dish",
      "Adapts recipes for dietary restrictions instantly",
    ],
    tags: ["cooking", "recipes", "food"],
  },
  {
    id: "2",
    slug: "cold-email-writer",
    name: "Cold Email Writer",
    creator: "@salesguru",
    category: "Sales",
    emoji: "📧",
    rating: 4,
    ratingCount: 91,
    price: "£2.99",
    priceType: "paid",
    downloads: "891",
    description: "Craft cold emails that actually get replies. This skill teaches your AI the art of personalised outreach — subject lines, hooks, CTAs, and follow-up sequences.",
    bullets: [
      "Generates personalised subject lines that get opened",
      "Writes concise, human-sounding email bodies",
      "Builds multi-touch follow-up sequences",
      "A/B tests different angles automatically",
    ],
    tags: ["sales", "email", "outreach"],
  },
  {
    id: "3",
    slug: "seo-content-engine",
    name: "SEO Content Engine",
    creator: "@rankmaster",
    category: "SEO",
    emoji: "🔍",
    rating: 4,
    ratingCount: 134,
    price: "£0.99/mo",
    priceType: "rental",
    downloads: "1.2k",
    description: "Turn your AI into an SEO powerhouse. Research keywords, generate structured content outlines, and write copy optimised to rank on Google — all in one skill.",
    bullets: [
      "Keyword research and clustering built-in",
      "Generates SEO-optimised article outlines",
      "Writes meta titles and descriptions",
      "Internal linking suggestions for existing content",
    ],
    tags: ["seo", "content", "writing"],
  },
  {
    id: "4",
    slug: "python-code-reviewer",
    name: "Python Code Reviewer",
    creator: "@bytewitch",
    category: "Development",
    emoji: "💻",
    rating: 5,
    ratingCount: 312,
    price: "Free",
    priceType: "free",
    downloads: "3.1k",
    description: "Add expert-level Python code review capabilities to your AI. Spots bugs, suggests refactors, checks PEP8 compliance, and explains issues clearly.",
    bullets: [
      "Catches common Python anti-patterns and bugs",
      "Suggests idiomatic refactors and improvements",
      "Checks PEP8 and type hint compliance",
      "Explains every suggestion with clear reasoning",
    ],
    tags: ["python", "code", "review", "dev"],
  },
  {
    id: "5",
    slug: "pitch-deck-builder",
    name: "Pitch Deck Builder",
    creator: "@vcwhisperer",
    category: "Business",
    emoji: "📊",
    rating: 4,
    ratingCount: 67,
    price: "£4.99",
    priceType: "paid",
    downloads: "567",
    description: "Build investor-ready pitch decks from scratch. This skill knows what VCs want to see: problem, solution, market size, traction, team, and ask.",
    bullets: [
      "Generates slide-by-slide pitch deck structure",
      "Crafts compelling problem/solution narratives",
      "Helps size TAM/SAM/SOM for any market",
      "Writes the founder story and team slide",
    ],
    tags: ["business", "startup", "pitch", "investors"],
  },
  {
    id: "6",
    slug: "recipe-innovator",
    name: "Recipe Innovator",
    creator: "@chefai",
    category: "Cooking",
    emoji: "🍳",
    rating: 3,
    ratingCount: 45,
    price: "Free",
    priceType: "free",
    downloads: "432",
    description: "Push culinary boundaries with AI-generated fusion recipes. Combines flavour science with creative experimentation to produce genuinely novel dishes.",
    bullets: [
      "Invents fusion recipes from two cuisine styles",
      "Applies flavour science principles to pairings",
      "Scales recipes up or down to any serving size",
      "Suggests Instagram-worthy plating techniques",
    ],
    tags: ["cooking", "creative", "fusion"],
  },
  {
    id: "7",
    slug: "linkedin-ghostwriter",
    name: "LinkedIn Ghostwriter",
    creator: "@postmaster",
    category: "Writing",
    emoji: "✍️",
    rating: 4,
    ratingCount: 88,
    price: "£1.99/mo",
    priceType: "rental",
    downloads: "743",
    description: "Write viral LinkedIn posts in seconds. This skill captures your voice and creates hooks, stories, and threads that build your personal brand.",
    bullets: [
      "Generates hooks that stop the scroll",
      "Adapts to your personal writing voice",
      "Creates carousel and story post formats",
      "Schedules a 30-day content calendar",
    ],
    tags: ["writing", "linkedin", "content"],
  },
  {
    id: "8",
    slug: "market-research-analyst",
    name: "Market Research Analyst",
    creator: "@datadigger",
    category: "Research",
    emoji: "🔬",
    rating: 5,
    ratingCount: 156,
    price: "£3.99",
    priceType: "paid",
    downloads: "1.8k",
    description: "Deep-dive into any market in minutes. Competitive analysis, customer personas, trend forecasting — without the expensive consultancy bill.",
    bullets: [
      "Builds comprehensive competitor matrices",
      "Creates detailed customer persona profiles",
      "Identifies emerging trends from first principles",
      "Produces SWOT and Porter's Five Forces analysis",
    ],
    tags: ["research", "market", "analysis"],
  },
  {
    id: "9",
    slug: "beat-maker-brief",
    name: "Beat Maker Brief",
    creator: "@loopcraft",
    category: "Music",
    emoji: "🎵",
    rating: 4,
    ratingCount: 52,
    price: "Free",
    priceType: "free",
    downloads: "621",
    description: "Brief your AI music producer like a pro. Describe a vibe and get detailed production notes, BPM, key, chord progressions, and sample suggestions.",
    bullets: [
      "Translates vibes into production specs",
      "Suggests BPM, key, and chord progressions",
      "Recommends sample packs and synthesiser patches",
      "Creates reference track playlists for mood",
    ],
    tags: ["music", "production", "creative"],
  },
  {
    id: "10",
    slug: "legal-doc-drafterj",
    name: "Legal Doc Drafter",
    creator: "@legalbot",
    category: "Business",
    emoji: "📊",
    rating: 4,
    ratingCount: 73,
    price: "£5.99",
    priceType: "paid",
    downloads: "389",
    description: "Draft standard business documents without a lawyer. NDAs, freelance contracts, Terms of Service — generated in minutes, not hours.",
    bullets: [
      "Drafts NDAs, contracts, and agreements",
      "Includes jurisdiction-appropriate clauses",
      "Plain-English explanations of each section",
      "Flags areas that need professional legal review",
    ],
    tags: ["legal", "business", "documents"],
  },
  {
    id: "11",
    slug: "twitter-thread-master",
    name: "Twitter Thread Master",
    creator: "@threadking",
    category: "Writing",
    emoji: "✍️",
    rating: 4,
    ratingCount: 201,
    price: "Free",
    priceType: "free",
    downloads: "2.2k",
    description: "Turn any idea into a viral Twitter thread. Hook, substance, and CTA — structured for maximum engagement and follows.",
    bullets: [
      "Crafts high-retention thread structures",
      "Writes punchy sub-200 character tweets",
      "Adds data, stories, and examples intelligently",
      "Optimises final CTA for follows or clicks",
    ],
    tags: ["writing", "twitter", "social"],
  },
  {
    id: "12",
    slug: "product-description-engine",
    name: "Product Description Engine",
    creator: "@convertswell",
    category: "Sales",
    emoji: "📧",
    rating: 5,
    ratingCount: 118,
    price: "£1.49",
    priceType: "paid",
    downloads: "934",
    description: "Write product descriptions that sell. E-commerce optimised copy that combines benefit-led writing with SEO keywords for any product category.",
    bullets: [
      "Benefit-led product description writing",
      "Weaves in SEO keywords naturally",
      "Multiple length variants (short, medium, long)",
      "A+ content format for Amazon listings",
    ],
    tags: ["ecommerce", "sales", "copywriting"],
  },
];

export const CATEGORIES = [
  { name: "Cooking", emoji: "🍳" },
  { name: "Development", emoji: "💻" },
  { name: "Writing", emoji: "✍️" },
  { name: "Sales", emoji: "📧" },
  { name: "SEO", emoji: "🔍" },
  { name: "Research", emoji: "🔬" },
  { name: "Music", emoji: "🎵" },
  { name: "Business", emoji: "📊" },
];

export const MOCK_REVIEWS = [
  {
    username: "@techdev_finn",
    stars: 5,
    date: "March 2025",
    body: "Absolutely game-changing. Integrated this into my daily workflow and it saved me hours every week. The quality of output is remarkable — feels like having a specialist on call.",
  },
  {
    username: "@sarahbuilds",
    stars: 4,
    date: "February 2025",
    body: "Really solid skill. Does exactly what it says on the tin. Minor gripe: would love a few more examples in the skill file itself, but the core functionality is excellent.",
  },
  {
    username: "@nomadmarketer",
    stars: 5,
    date: "January 2025",
    body: "Best skill I've downloaded on Hermitcrab so far. The creator clearly knows their stuff. Already recommended it to three colleagues.",
  },
];
